
#Redis
spring:
  redis:
    sentinel:
        master: mymaster
        nodes: 192.168.226.134:26379
    #host: 192.168.226.133
    ## Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
    #port: 26379
    ## \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
    #timeout: 300
    ## Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
    password: redis@2019
    ## \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u8FDE\u63A5\u6570
   # poolMaxTotal: 10
    ## \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
   # poolMaxIdle: 10
    ## \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
    #poolMaxWait: 3
    jedis:
      pool:
        max-active: 10
        max-wait: 500
        min-idle: 1
        time-between-eviction-runs: 300
  datasource:
    username: mzgh
    password: Mzgh@2019
    url: jdbc:mysql://192.168.226.134:3307/mzgh?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
#mybatis:
  #mapper-locations: classpath:/mybaits/mapper/*.xml
  #config-location:  classpath:/mybatis/config/mybatis-config.xml
zk:
  url: 192.168.226.134:2181
